name: Check Assignments and Attendance
on:
  schedule:
    - cron: '0 3,9,13 * * *' # Modify to your preference
  workflow_dispatch: # Manual trigger for testing

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          pip install playwright requests python-dotenv
          playwright install --with-deps chromium
      
      - name: Run Script
        env:
          ENROLLMENT_NUMBER: ${{ secrets.ENROLLMENT_NUMBER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          NTFY_SERVER: ${{ secrets.NTFY_SERVER }}
          NOTIFICATION_LEVEL: ${{ secrets.NOTIFICATION_LEVEL || '0' }}
          NOTIFY_SUBMITTED: ${{ secrets.NOTIFY_SUBMITTED || '1' }}
          NOTIFY_EXTENDED: ${{ secrets.NOTIFY_EXTENDED || '1' }}
          INSTITUTION: ${{ secrets.INSTITUTION || '6' }}
          DOWNLOAD_ASSIGNMENTS: ${{ secrets.DOWNLOAD_ASSIGNMENTS || '0' }}
        
        run: |
          set +e
          python githubActions.py 
          python checkAttendance.py